#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       The Vacui filesystem workspace
#

[general]
type = "workspace"

[info.workspace]
modules = [
   "lib"
]
