# 
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
#       The vqfs_fmt Makefile
# 

FLAGS_C += --std=c23 -I../../inc

include ../../../../templates/x86_64-linux-program.mk