#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
# 		Hlb Video library configuration
# 

[general]
type = "regular"

[info.regular]
target_path = "libhlbvid.a"
sources = ["main.c"]
objs_dir = ".objs"
