# 
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
#       The main Vacui workspace
# 

[general]
type = "workspace"

[info.workspace]
modules = [
    "base",
]
