#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       The bsl_host Makefile
#

FLAGS_C += -I../inc/
LIBRARY_TYPE := static

include ../../../templates/x86_64-linux-library.mk
