#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       The bsl_host config
#

[general]
type = "regular"

[info.regular]
target_path = "libbsl_host.a"
sources = ["meta.c", "mm.c"]
objects_dir = ".objs"
forced_toolchain = "../../../toolchains/x86_64-linux.toml"
