# Copyright 2026 - Apache License 2.0
# A part of https://github.com/dywoq/zero

SRC += hub/start.S hub/hub.c \
	   hub/panic.c hub/print.c

OBJ += $(BUILD)/hub/start.o $(BUILD)/hub/hub.o \
       $(BUILD)/hub/panic.o $(BUILD)/hub/print.o
