# 
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
#       The vqfs_write config
# 

[general]
type = "regular"

[info.regular]
target_path = "vqfs_write"
sources = ["main.c"]
objects_dir = ".objs"
forced_toolchain = "../../../../toolchains/x86_64-linux.toml"
