#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       VQBoot sector stage configuration
#

[general]
type = "regular"

[info.regular]
target_path = "vqbootsector.bin"
sources = [
    "sector.S"
]
objs_dir = ".objs"
