#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
#       VQBoot sector stage Makefile
#

include ../../../templates/x86_16-bare-metal-program.mk
