#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       VQBoot primary stage configuration
#

[general]
type = "regular"

[info.regular]
target_path = "vqbootprimary.bin"
sources = [
    "startup.S",
    "entry.c",
    "print.c"
]
objs_dir = ".objs"
dependencies = [
    "../../hlb/vid",
    "../../hlb/disk"
]
