#!/usr/bin/python

# Copyright 2026 dywoq - Apache License 2.0
# A part of https://github.com/dywoq/vacui

import argparse
import os
import sys

autoconf_path = "include/vacui/kernel/autoconf.h"
config_path = ".config"


def main():
    parser = argparse.ArgumentParser(
        prog="gen-kconfig.py",
        description="Generate configuration header from Kconfig."
    )
    parser.parse_args()

    os.makedirs("include/vacui/kernel/", exist_ok=True)

    try:
        import kconfiglib
    except ImportError:
        print("Error: kconfiglib is required. Install it with: pip install kconfiglib")
        sys.exit(1)

    try:
        kconf = kconfiglib.Kconfig("Kconfig")
        kconf.load_config(config_path)
        kconf.write_autoconf(autoconf_path)
        kconf.write_config(config_path)
    except Exception as e:
        print(f"Error: Failed to process Kconfig: {e}")
        sys.exit(1)

    try:
        with open(autoconf_path, "r") as f:
            content = f.read()
    except FileNotFoundError:
        print("Error: autoconf.h not found after generation")
        sys.exit(1)
    except PermissionError:
        print("Error: Permission denied reading autoconf.h")
        sys.exit(1)

    try:
        with open(autoconf_path, "w") as f:
            f.write("// Copyright 2026 dywoq - Apache License 2.0\n")
            f.write("// A part of https://github.com/dywoq/vacui\n\n")
            f.write("#ifndef _VACUI_KERNEL_AUTOCONF_H\n")
            f.write("#define _VACUI_KERNEL_AUTOCONF_H\n\n")
            f.write("// It's automatically generated by scripts/gen-kconfig.py\n")
            f.write("// DO NOT EDIT\n\n")
            f.write(content)
            f.write("\n#endif\n")
    except PermissionError:
        print("Error: Permission denied writing autoconf.h")
        sys.exit(1)


if __name__ == "__main__":
    main()
