# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui

all:
	make clean all -C sector
	make clean all -C primary
	make all -C final
	
clean:
	make clean -C sector
	make clean -C primary
	make clean -C final
