#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
#       VQBoot sector stage Makefile
#

LINKER_ENTRY_FUNCTION := SectorEntry
LINKER_ADDRESS := 0x7c00
include ../../../templates/x86_16-bare-metal-program.mk
