// Copyright 2026 dywoq - Apache License 2.0
// A part of https://github.com/dywoq/zero

#ifndef _ZERO_BOOT_LOAD_AUTOCONF_H
#define _ZERO_BOOT_LOAD_AUTOCONF_H

// It's automatically generated by gen.py
// DO NOT EDIT


#endif
