#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
# 		Hlb Video library Makefile
# 

FLAGS_C := -I../inc -I../../inc -std=c23
LIBRARY_TYPE := static
include ../../templates/x86_16-bare-metal-library.mk
