#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       The Vacui filesystem library Makefile
#

FLAGS_C := -std=c23 -I../inc/
LIBRARY_TYPE := static

include $(VACUI_TEMPLATES)/x86_64-linux-library.mk
