# Copyright 2026 dywoq - Apache License 2.0
# A part of https://github.com/dywoq/zero

import os
import sys

try:
    import kconfiglib
except ImportError:
    print("Error: kconfiglib is required. Install it with: pip install kconfiglib")
    sys.exit(1)

try:
    kconf = kconfiglib.Kconfig("Kconfig")
    kconf.load_config(".config")
    kconf.write_autoconf("include/zero/autoconf.h")
    kconf.write_config(".config")
except Exception as e:
    print(f"Error: Failed to process Kconfig: {e}")
    sys.exit(1)

try:
    with open("include/zero/autoconf.h", "r") as f:
        content = f.read()
except FileNotFoundError:
    print("Error: autoconf.h not found after generation")
    sys.exit(1)
except PermissionError:
    print("Error: Permission denied reading autoconf.h")
    sys.exit(1)

try:
    with open("include/zero/autoconf.h", "w") as f:
        f.write("// Copyright 2026 dywoq - Apache License 2.0\n")
        f.write("// A part of https://github.com/dywoq/zero\n\n")
        f.write("#ifndef _ZERO_AUTOCONF_H\n")
        f.write("#define _ZERO_AUTOCONF_H\n\n")
        f.write("// It's automatically generated by scripts/kconfig/gen.py\n")
        f.write("// DO NOT EDIT\n\n")
        f.write(content)
        f.write("\n#endif\n")
except PermissionError:
    print("Error: Permission denied writing autoconf.h")
    sys.exit(1)

