# Copyright 2026 dywoq - Apache License 2.0
# A part of https://github.com/dywoq/zero

import os
import kconfiglib

kconf = kconfiglib.Kconfig("Kconfig")
kconf.load_config(".config")
kconf.write_autoconf("include/zero/boot/load/autoconf.h")
kconf.write_config(".config")

with open("include/zero/boot/load/autoconf.h", "r") as f:
    content = f.read()

with open("include/zero/boot/load/autoconf.h", "w") as f:
    f.write("// Copyright 2026 dywoq - Apache License 2.0\n")
    f.write("// A part of https://github.com/dywoq/zero\n\n")
    f.write("#ifndef _ZERO_BOOT_LOAD_AUTOCONF_H\n")
    f.write("#define _ZERO_BOOT_LOAD_AUTOCONF_H\n\n")
    f.write("// It's automatically generated by gen.py\n")
    f.write("// DO NOT EDIT\n\n")
    f.write(content)
    f.write("\n#endif\n")

