#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Module Description
#
#       VQBoot workspace config
#

[general]
type = "workspace"

[info.workspace]
modules = [
    "sector",
    "primary"
]
