#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
# 
# Module Description
# 
# 		Makefile of vqfs_format command utility
# 

FLAGS_C := -I../../fs/inc/ -std=c23

include ../../templates/x86_64-elf-program.mk
