#
# Copyright 2026 dywoq - Apache License 2.0
# https://github.com/dywoq/vacui
#
# Routine Description
# 
#       Toolchain for building bare-metal programs, libraries etc. for 
#       x86_16 (real mode).
# 
#       Although the linker and compiler flags declare a 32-bit environment, 
#       you still must use ".code16gcc" at the start of your source files
#       (in assembly files, you use "bits 16" directive).
# 
#       The Makefile templates, associated with this toolchain, are 
#       private/templates/x86_16-bare-metal-*.mk files. You should use include in
#       Makefile of components.
#

compiler_c = "gcc"
compiler_cxx = "g++"
linker = "ld"
assembly = "nasm"
additional_flags_c = [
    "-ffreestanding",
    "-nostdlib",
    "-nostdinc",
    "-m32",
    "-fno-pic",
    "-fno-stack-protector"
]
additional_flags_cxx = [
    "-ffreestanding",
    "-nostdlib",
    "-nostdinc",
    "-m32",
    "-fno-pic",
    "-fno-stack-protector"
]
additional_flags_linker = [
    "-m", "elf_i386",
    "-no-pie",
]
additional_flags_assembly = [
    "-f", "elf32"
]
