#
# Copyright 2026 dywoq - Apache License 2.0 
# https://github.com/dywoq/vacui
#
# Routine Description
#
# 	Makefile for building HLB (High-level BIOS) library
#

FLAGS_C 	:= -I../inc/ -I../../inc/ -std=c23
LIBRARY_TYPE := static

include ../../templates/x86_16-bare-metal-library.mk
